arch:
  - amd64
  - ppc64le

sudo: false
language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - master
  - tip

before_script: 
  #- ls -la /home/travis/.gimme/versions/go1.6.src/
  #- ls -la /home/travis/.gimme/versions/
  #- ls -la /home/travis/.gimme/
  - unset GOROOT

script: make test
